name: Post AI News

on:
  schedule:
    - cron: "*/30 * * * *"   # هر 30 دقیقه
  workflow_dispatch:          # اجرای دستی

permissions:
  contents: write

concurrency:
  group: post-ai-news
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check secrets presence
        run: |
          test -n "${{ secrets.TELEGRAM_TOKEN }}" && echo "TELEGRAM_TOKEN=OK" || (echo "TELEGRAM_TOKEN=MISSING" && exit 1)
          test -n "${{ secrets.CHANNEL_USERNAME }}" && echo "CHANNEL_USERNAME=OK" || (echo "CHANNEL_USERNAME=MISSING" && exit 1)
          test -n "${{ secrets.HF_TOKEN }}" && echo "HF_TOKEN=OK" || (echo "HF_TOKEN=MISSING (will skip HF)" )

      # —— مرحلهٔ تشخیصی مفصل تلگرام ——
      - name: Telegram diagnostics
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHANNEL_USERNAME: ${{ secrets.CHANNEL_USERNAME }}
        run: |
          set -e
          echo "== getMe =="
          curl -s "https://api.telegram.org/bot${TELEGRAM_TOKEN}/getMe"; echo; echo

          echo "== getChat (using CHANNEL_USERNAME as chat_id) =="
          curl -s "https://api.telegram.org/bot${TELEGRAM_TOKEN}/getChat" \
               -d chat_id="${CHANNEL_USERNAME}"; echo; echo

          BOT_ID=$(cu_
